### ISSUE TITLE
DELETE THE REPO

### ISSUE THREAD

**Issue by Derek1199** [gitgud1111/gitgud#1]
THIS SHOULDN'T BE OPEN SOURCE. DELETE IT DELETE IT DELETE IT DELETE IT. DELETE IT.
REEEEEEEEEEEEEEEE *Austic screeching* DELETE IT HARDER DADDY. DELETE IT. BRICK MAH DICK AND DELETE THE REPO OOOOOOOOOOO REEEEEEEEEEEEE This is my mating call. SERIOUSLY THOUGH DELETE THIS SHITTY PROJECT. :3

**Comment by gitgud1111** [comment]
Sorry, but this project is solely for allowing server administrators to stress test their own anti-spam bots. I do not take responsibility for what they do with it, so I don't see any point in deleting a very valid project.

Also, maybe if you acted more professional, you'd get farther.

**Comment by astronautlevel2** [comment]
I'm going to point out that, despite your supposed intentions for this repo, people are clearly going to use this to raid - it's up to you as a developer to look at your morals and consider whether you're alright with people using it for that.

On the other hand, I agree that this issue was... cringey at best.

**Comment by gitgud1111** [comment]
People will probably use it for raiding, and those people will probably be banned.

I still am going to keep this up because it may help people stress test their own servers.
